# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: yarn

      # Runs a set of commands using the runners shell
      - name: Build dist
        run: yarn build

      - name: Push to release branch
        run: |
          git config --global user.email "aleksandar.v.rajic@gmail.com"
          git config --global user.name "Aleksandar Rajic"
          rm -rf build/
          mkdir build
          mv dist/* build/
          git add .
          git commit -m "release: latest deployment"
          git checkout latest_release
          git merge master
